Presentation/MyBookstore.Web/Controllers/AddToCartController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MyBookstore.Core;
using MyBookstore.Models;
using MyBookstore.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Http;
using System.Threading.Tasks;
using System.Data;
using System.Configuration;
using System.Web;
using System.Xml.Linq;

namespace MyBookstore.Web.Controllers
{
    public class AddToCartController : Controller
    {

        IHostingEnvironment _appEnvironment;
        private readonly IUserService _userServices;
        private readonly IMailingService _mailingService;
        private readonly UserManager<ApplicationUser> _userManager;
        

        public AddToCartController(IUserService userServices, IHostingEnvironment appEnvironment, IMailingService mailingService, UserManager<ApplicationUser> userManager)
        {
            _appEnvironment = appEnvironment;
            _userServices = userServices;
            _userManager = userManager;
            _mailingService = mailingService;

        }

               // GET: /<controller>/
        public IActionResult Index()
        {

            return View();
        }

        public ActionResult Add(BookViewModel book)
        {

            //if (Session["cart"] == null)
            //{
            //    List<BookViewModel> li = new List<BookViewModel>();

            //    li.Add(book);
            //    Session["cart"] = li;
            //    ViewBag.cart = li.Count();


            //    Session["count"] = 1;


            //}
            //else
            //{
            //    List<BookViewModel> li = (List<BookViewModel>)Session["cart"];
            //    li.Add(book);
            //    Session["cart"] = li;
            //    ViewBag.cart = li.Count();
            //    Session["count"] = Convert.ToInt32(Session["count"]) + 1;

            //}
            return RedirectToAction("Index", "Home");


        }

    }
}

Presentation/MyBookstore.Web/Controllers/HomeController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MyBookstore.Services;
using MyBookstore.Core;
using MyBookstore.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;

namespace MyBookstore.Web
{
    public class HomeController : BaseController
    {

        IHostingEnvironment _appEnvironment;
        private readonly IMyBookstoreService _myBookstoreService;
        private readonly IAuthorService _authorsServices;
        private readonly IBookService _booksServices;

        public HomeController(IMyBookstoreService myBookstoreService, IHostingEnvironment appEnvironment, IAuthorService authorsServices, IBookService booksServices, UserManager<ApplicationUser> userManager) : base(userManager)
        {
            _appEnvironment = appEnvironment;
            _myBookstoreService = myBookstoreService;
            _authorsServices = authorsServices;
            _booksServices = booksServices;
        }


        public async Task<IActionResult> Index(HomePageViewModel model)
        {
            ViewData["SurnameSort"] = model.SortOrder = String.IsNullOrEmpty(model.SortOrder) ? "Surname_Asc" : "";
            return View(await _myBookstoreService.GetHomePageAsync(model.SortOrder, model.AuthorIdSearchParameter, model.BookNameSearchParameter, model.PageNumber, await GetCurrentUserAsync()));
        }

        public async Task<IActionResult> GetBooks()
        {
            return View(await _booksServices.GetBooksAsync());
        }

        [HttpGet]
        public async Task<IActionResult> AddBook()
        {
            var authors = await _booksServices.AuthorDropdownAsync();
            ViewBag.Authors = authors;

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> EditBook(int id)
        {

            var authors = await _booksServices.AuthorDropdownAsync();
            ViewBag.Authors = authors;


            return View();
        }


        [HttpPost]

        public async Task<IActionResult> EditBook(Book b)
        {
            if (ModelState.IsValid)

            {
                await _booksServices.UpdateBook(b);

                return RedirectToAction("Index");
            }
            return View(b);


        }





    }
}

Presentation/MyBookstore.Web/Controllers/ShoppingCartController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MyBookstore.Services;
using MyBookstore.Core;
using MyBookstore.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;

namespace MyBookstore.Web
{
    public class ShoppingCartController : BaseController
    {

        IHostingEnvironment _appEnvironment;
        private readonly IShoppingCartService _shoppingCartService;

        public ShoppingCartController(IShoppingCartService shoppingCartService, UserManager<ApplicationUser> userManager) : base(userManager)
        {
            _shoppingCartService = shoppingCartService;
        }

        [Route("/ShoppingCart")]
        public async Task<IActionResult> Index()
        {
            var model = await _shoppingCartService.GetShoppingCartAsync(_userId);


            return View("~/Views/ShoppingCart/Index.cshtml", model);
        }

        [Route("/ShoppingCart/AddToCart/{bookId}")]
        public async Task<IActionResult> AddToCart(int bookId)
        {
            await _shoppingCartService.AddToCartAsync(bookId, _userId);
            return Redirect("/ShoppingCart");
        }

        [HttpGet("/ShoppingCart/RemoveFromCart/{itemId}")]
        public async Task<IActionResult> RemoveFromCart(int itemId)
        {
            await _shoppingCartService.RemoveFromCartAsync(itemId);
            return Redirect("/ShoppingCart");
        }


        [HttpGet("/ShoppingCart/RemoveFromCart")]
        public async Task<IActionResult> RemoveAllFromCart(Guid userId)
        {
            await _shoppingCartService.RemoveAllFromCartAsync(userId);
            return Redirect("/ShoppingCart");
        }


    }
}

Presentation/MyBookstore.Web/Views/Home/Details.cshtml
@using MyBookstore.Models;
@model MyBookstore.Models.BookViewModel;


<div>
    <h4>Book Information</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>

            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Author.MiddleName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Author.Surname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PaperBook)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BookFormats)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsAvailable)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Reviews)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Index") |

</p>

Presentation/MyBookstore.Web/Views/Home/Edit.cshtml
@using MyBookstore.Models;
@model MyBookstore.Models.HomePageViewModel;


@{
    ViewData["Title"] = "Home";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="referrer" content="no-referrer" />
    <title>MyBookstore</title>
    <link rel="stylesheet" href="/style/bootstrap.css">
</head>
<body>

    <h2>Edit</h2>
    
    <div>
        <h3>Our Authors</h3>
        <table class="table">
            <thead>
                <tr>
                    <td><p> Surname</p></td>
                    <td><p> Name</p></td>
                    <td><p> Middlename</p></td>
                    <td><p>More...</p></td>
                    <td></td>
                </tr>
            </thead>
            <tbody>
                @foreach (AuthorViewModel a in @Model.Authors)
            {
                <tr>
                    <td><p>@a.Surname</p></td>
                    <td><p>@a.Name</p></td>
                    <td><p>@a.MiddleName</p></td>
                    <td><p><a href="/Home/Author/@a.AuthorId">More info & reviews</a></p></td>
                </tr>
        }
            </tbody>
        </table>
        </div>

            <a href="/home/edit" class="btn btn-lg btn-primary">Add new author</a>

</body>
</html>

Presentation/MyBookstore.Web/Views/Home/Index.cshtml
@using MyBookstore.Models;
@model MyBookstore.Models.HomePageViewModel ;
@{
    Layout = "~/Views/Layout.cshtml";
}

@using (Html.BeginForm("Index", "Home", FormMethod.Post, new { id = "Form Name" }))
{
    <br>
    <div>

        <a href="/Authors/EditAuthor" class="btn btn-dark">Add new author</a>
        <a href="/Books/EditBook/new" class="btn btn-dark">Add New Book</a>
    </div>
    <br>
    <div class="alert alert-dark" role="alert" it>
        <a href="#" class="alert-link">NEWS and NEW ARRIVALS</a>
    </div>

    <div class="container">
        <div class="row">

            <div id="carouselExampleControls" class="carousel slide" data-ride="carousel" style=" width:100%;">
                <div style="margin-bottom:20px;">
                    <div style="float:left;">
                        <a class="" href="#carouselControls" role="button" data-slide="prev">
                            <span>Previous</span>
                        </a>
                    </div>
                    <div style="float:right;">
                        <a class="" href="#carouselControls" role="button" data-slide="next">
                            <span>Next</span>
                        </a>
                    </div>
                    <div style="clear:both;">
                        </div>
                </div>

                <div class="carousel-inner" style="height: 550px !important;">

                    @{var carouselSize = 4;}

                    <div class="container">
                        <div class="row">
                            <div id="carouselControls" class="carousel slide" data-ride="carousel">
                                <div class="carousel-inner">
                                    @for (int p = 0; p < Model.CarouselBooks.Count % carouselSize; p++)
                                    {
                                        <div class="@(p==0 ? "carousel-item active" : "carousel-item")">
                                            <div class="row">

                                                @foreach (var book in Model.CarouselBooks.Skip(p * carouselSize).Take(carouselSize))
                                                {
                                                    <div class="col-sm-3">
                                                        <div class="col-item">

                                                            <div class="photo">
                                                                <img src="@Html.Raw(String.IsNullOrEmpty(book.ThumbnailName) ? "/Images/Uploads/Default.jpg" : "/Images/Uploads/" + book.ThumbnailName)" style="width:260px; height:300px;" class="img-responsive" alt="a" />
                                                            </div>


                                                            <div class="info">
                                                                <div class="row">
                                                                    <div class="price col-md-12">
                                                                        <h5>
                                                                            @book.Name

                                                                        </h5>

                                                                        <h5 class="price-text-color">
                                                                            @book.Price
                                                                        </h5>

                                                                        <h5 class="price-text-color">
                                                                            @Html.ActionLink("More details", "ShowBook", "Books", new { id = book.BookId })
                                                                        </h5>

                                                                        <h5 class="price-text-color">
                                                                            @Html.ActionLink("Add to Cart", "AddToCart", "ShoppingCart", new { id = book.BookId })
                                                                        </h5>

                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                }

                                            </div>
                                        </div>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>




                </div>

            </div>


        </div>
    </div>











    @*<div class="container">
        <div class="row">
            <div class="row">
                <div class="col-md-12">*@
    <h4>
        Readers' Club Choice
    </h4>
    @*</div>*@
    <div class="col-md-10">
        <!-- Controls -->
        <div class="controls pull-right hidden-xs">
            <a class="left fa fa-chevron-left btn btn-success" href="#carousel-example"
               data-slide="prev"></a>

            <a class="right fa fa-chevron-right btn btn-success" href="#carousel-example"
               data-slide="next"></a>
        </div>
    </div>

    <div id="carousel-example" class="carousel slide hidden-xs" data-ride="carousel">
        <!-- Wrapper for slides -->
        <div class="carousel-inner">
            @for (int r = 0; r < (Model.CarouselBooks.Count % 4); r++)
            {
                <div class="@Html.Raw(r == 0 ?"item active":"item")">
                    <div class="row">

                        @foreach (var book in Model.CarouselBooks.Skip(r * 4).Take(4))
                        {
                            <div class="col-sm-3">
                                <div class="col-item">
                                    <div class="photo">
                                        <img src="@Html.Raw(String.IsNullOrEmpty(book.ThumbnailName) ?  "/Images/Uploads/Default.jpg"  : "/Images/Uploads/"+book.ThumbnailName)" style="width:200px; height:300px;" alt="a" />
                                    </div>
                                    <div class="info">
                                        <div class="row">
                                            <div class="price col-md-6">
                                                <h5>
                                                    @book.Name

                                                </h5>

                                                <h5 class="price-text-color">
                                                    @book.Price
                                                </h5>
                                            </div>
                                            <div class="rating hidden-sm col-md-6">
                                                <i class="price-text-color fa fa-star"></i><i class="price-text-color fa fa-star">
                                                </i><i class="price-text-color fa fa-star"></i><i class="price-text-color fa fa-star">
                                                </i><i class="fa fa-star"></i>
                                            </div>
                                        </div>
                                        <div class="separator clear-left">
                                            <p class="btn-add">
                                                <i class="fa fa-shopping-cart"></i><a href="http://www.jquery2dotnet.com" class="hidden-sm">Add to cart</a>
                                            </p>
                                            <p class="btn-details">
                                                <i class="fa fa-list"></i>

                                            <p>
                                                @Html.ActionLink("More details", "ShowBook", "Books", new { id = book.BookId })

                                            </p>
                                        </div>
                                        <div class="clearfix">
                                        </div>
                                    </div>
                                </div>
                            </div>

                        }
                    </div>
                </div>
            }
        </div>
    </div>
    @*</div>
        </div>*@








    <h1>Our Books</h1>

    <form method="get">
        <div class="form-inline form-group">
            <label class="control-label">Book: </label>
            <input type="text" name="BookNameSearchParameter" value="@ViewData["currentFilter"]" />
            @*@Html.TextBox("BookNameSearchParameter", Model.BookNameSearchParameter, htmlAttributes: new { @class = "form-control" })*@

            <label class="control-label">Author: </label>
            @Html.DropDownList("AuthorIdSearchParameter", Model.Authors.Select(t => new SelectListItem()
            {
                Text = t.Name + " " + t.Surname,
                Value = t.AuthorId.ToString()
            }), "Any",


                                                                                                                                                                                                                       htmlAttributes: new { @class = "form-control" })

            <input type="submit" value="Filter" class="btn btn-default" />
        </div>
    </form>










    <table class="table">
        <thead>
            <tr>
                <td><p> Title</p></td>
                <td><p> Author</p></td>
                <td><p> Description</p></td>
                <td><p>More...</p></td>
                <td></td>
            </tr>
        </thead>
        <tbody>
            @foreach (var b in @Model.Books)
            {
                <tr>
                    <td><p>@b.Name</p></td>
                    <td><p>@b.Author.Surname</p></td>
                    <td><p>@b.Description</p></td>
                    <td><p>@Html.ActionLink("Open", "ShowBook", "Books", new { id = b.BookId })</p></td>
                </tr>
            }
        </tbody>
    </table>


    @if (Model.HasPreviousPage)
    {
        <a href="@Url.Action("Index", "Home", new { PageNumber = Model.PageNumber - 1 })"
           class="btn btn-lg btn-default">
            <<
        </a>
    }
    @Model.PageNumber

    @if (Model.HasNextPage)
    {

        <a href="@Url.Action("Index", "Home",new {PageNumber = Model.PageNumber + 1 } )"
           class="btn btn-lg btn-default">
            >>
        </a>
    }








}

Presentation/MyBookstore.Web/Views/Home/IndexOLD.cshtml
<body>
    <section class="gallery-block cards-gallery">
        <div class="container">
            <div class="heading">
                <h2>Cards Gallery</h2>
            </div>
            <div class="row">

                @if (Model.ThumbnailName != null)
                {
                    var imagePath = "";
                    foreach (var p in Model.Pictures.Where(n => n.BookId == Model.BookId && n.Main != true))
                    {

                        imagePath = @"/Images/Uploads/" + p.Id + "_" + p.Name.ToString();

                        <div class="card border-0 transform-on-hover">
                            <a class="lightbox" href="@imagePath">
                                <img src="@imagePath" style='width:150px; height:200px;' alt="Card Image" class="card-img-top">
                            </a>
                            <div class="card-body">
                                <h6><a href="#">Lorem Ipsum</a></h6>
                                <p class="text-muted card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc quam urna.</p>
                            </div>

                        </div>
                    }
                }


            </div>
        </div>
    </section>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.js"></script>
    <script>
        baguetteBox.run('.cards-gallery', { animation: 'slideIn' });
    </script>
</body>
</html>

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Cards Gallery</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.css" />
    <link rel="stylesheet" href="cards-gallery.css">
</head>
<body>
    <section class="gallery-block cards-gallery">
        <div class="container">
            <div class="heading">
                <h2>Cards Gallery</h2>
            </div>
            <div class="row">
                <div class="col-md-6 col-lg-4">
                    <div class="card border-0 transform-on-hover">
                        <a class="lightbox" href="../img/image1.jpg">
                            <img src="../img/image1.jpg" alt="Card Image" class="card-img-top">
                        </a>
                        <div class="card-body">
                            <h6><a href="#">Lorem Ipsum</a></h6>
                            <p class="text-muted card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc quam urna.</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-4">
                    <div class="card border-0 transform-on-hover">
                        <a class="lightbox" href="../img/image2.jpg">
                            <img src="../img/image2.jpg" alt="Card Image" class="card-img-top">
                        </a>
                        <div class="card-body">
                            <h6><a href="#">Lorem Ipsum</a></h6>
                            <p class="text-muted card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc quam urna.</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-4">
                    <div class="card border-0 transform-on-hover">
                        <a class="lightbox" href="../img/image3.jpg">
                            <img src="../img/image3.jpg" alt="Card Image" class="card-img-top">
                        </a>
                        <div class="card-body">
                            <h6><a href="#">Lorem Ipsum</a></h6>
                            <p class="text-muted card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc quam urna.</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-4">
                    <div class="card border-0 transform-on-hover">
                        <a class="lightbox" href="../img/image4.jpg">
                            <img src="../img/image4.jpg" alt="Card Image" class="card-img-top">
                        </a>
                        <div class="card-body">
                            <h6><a href="#">Lorem Ipsum</a></h6>
                            <p class="text-muted card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc quam urna.</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-4">
                    <div class="card border-0 transform-on-hover">
                        <a class="lightbox" href="../img/image5.jpg">
                            <img src="../img/image5.jpg" alt="Card Image" class="card-img-top">
                        </a>
                        <div class="card-body">
                            <h6><a href="#">Lorem Ipsum</a></h6>
                            <p class="text-muted card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc quam urna.</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 col-lg-4">
                    <div class="card border-0 transform-on-hover">
                        <a class="lightbox" href="../img/image6.jpg">
                            <img src="../img/image6.jpg" alt="Card Image" class="card-img-top">
                        </a>
                        <div class="card-body">
                            <h6><a href="#">Lorem Ipsum</a></h6>
                            <p class="text-muted card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc quam urna.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.10.0/baguetteBox.min.js"></script>
    <script>
        baguetteBox.run('.cards-gallery', { animation: 'slideIn' });
    </script>




    <div data-app-prevent-settings="" class="mbr-slider modal fade carousel slide in" tabindex="-1" data-keyboard="true" data-interval="false" id="lb-gallery1-0" style="display: block;">
        <div class="modal-dialog" style="width: 224px; top: 10px;">
            <div class="modal-content">
                <div class="modal-body">
                    <ol class="carousel-indicators">
                        <li data-app-prevent-settings="" data-target="#lb-gallery1-0" data-slide-to="0"></li>
                        <li data-app-prevent-settings="" data-target="#lb-gallery1-0" data-slide-to="1" class="active"></li>
                        <li data-app-prevent-settings="" data-target="#lb-gallery1-0" data-slide-to="2" class=""></li>
                        <li data-app-prevent-settings="" data-target="#lb-gallery1-0" data-slide-to="3" class=""></li>
                        <li data-app-prevent-settings="" data-target="#lb-gallery1-0" data-slide-to="4" class=""></li>
                        <li data-app-prevent-settings="" data-target="#lb-gallery1-0" class="" data-slide-to="5"></li>
                        <li data-app-prevent-settings="" data-target="#lb-gallery1-0" data-slide-to="6"></li>
                    </ol>
                    <div class="carousel-inner">
                        <div class="carousel-item">
                            <img alt="jQuery Image Slider with Thumbnail" src="assets/images/pexels-photo-2000x1333-33.jpg">
                        </div><div class="carousel-item active">
                            <img alt="HTML Lightbox Free Download" src="assets/images/photo-1471914395157-f9d1b9dc592d6-2000x2800-8.jpg">
                        </div><div class="carousel-item">
                            <img alt="Image slideshow with thumbnail carousel" src="assets/images/photo-1471922651044-1105732198fb-2000x1331-89.jpg">
                        </div><div class="carousel-item">
                            <img alt="CSS Photo Lightbox with thumbnails" src="assets/images/pexels-photo-38196-2000x1333-8.png">
                        </div><div class="carousel-item">
                            <img alt="jQuery Picture Slider with Modal Popup" src="assets/images/photo-1432850252397-8be919d9ba23-2000x1333-90.jpg">
                        </div><div class="carousel-item">
                            <img alt="Mobile Video Slider with Lightbox" src="assets/images/photo-1462266160352-c606c50d44a9-2000x1333-16.jpg">
                        </div><div class="carousel-item video-container">
                            <img alt="Website photo carousel popup" src="http://img.youtube.com/vi/uNCr7NdOJgw/maxresdefault.jpg">
                            <iframe id="mbr-video-0" class="mbr-background-video" data-video-num="0" frameborder="0" allowfullscreen="1" allow="autoplay; encrypted-media" title="YouTube video player" width="100%" height="100%" src="https://www.youtube.com/embed/uNCr7NdOJgw?enablejsapi=1&amp;origin=https%3A%2F%2Fmobirise.com&amp;widgetid=1"></iframe><div class="item-overlay"></div>
                        </div>
                    </div>
                    <a class="left carousel-control" role="button" data-slide="prev" href="#lb-gallery1-0">
                        <span class="icon-prev" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="right carousel-control" role="button" data-slide="next" href="#lb-gallery1-0">
                        <span class="icon-next" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>

                    <a class="close" href="#" role="button" data-dismiss="modal">
                        <span aria-hidden="true">×</span>
                        <span class="sr-only">Close</span>
                    </a>
                </div>
            </div>